# --- logins schema
# --- To avoid constraint name conflict
# --- constraint_xxx were added to the CONSTRAINT name
# --- generated by MySQLWorkBench EER Model

# --- !Ups
CREATE TABLE IF NOT EXISTS `LOGINS` (
  `providerId` VARCHAR(45) NOT NULL,
  `providerKey` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`providerId`, `providerKey`),
  INDEX `key_idx` (`providerKey` ASC),
  CONSTRAINT `constraint_login_provider`
    FOREIGN KEY (`providerId`)
    REFERENCES `PROVIDERS` (`providerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `constraint_login_key`
    FOREIGN KEY (`providerKey`)
    REFERENCES `USERS` (`providerKey`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

# --- !Downs

DROP TABLE `LOGINS`;
