# --- authenticators schema
# --- To avoid constraint name conflict
# --- constraint_XXX were added to the CONSTRAINT name
# --- generated by MySQLWorkBench EER Model


# --- !Ups
CREATE TABLE IF NOT EXISTS `AUTHENTICATORS` (
  `provider` INT NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  `lastUsed` DATETIME NULL,
  `expiration` DATETIME NULL,
  `idleTimeOut` INT NULL,
  `duration` INT NULL,
  `id` VARCHAR(300) NOT NULL,
  INDEX `key_idx` (`key` ASC),
  PRIMARY KEY (`provider`, `key`)
);

# --- !Downs

DROP TABLE `AUTHENTICATORS`;
